@echo off
start /B python "G:\zed\mcp_servers\001-code-architect\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\002-python-weaver\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\003-web-sculptor\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\004-design-crafter\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\005-browser-engineer\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\006-devops-pilot\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\007-data-alchemist\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\008-api-builder\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\009-css-artisan\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\010-js-virtuoso\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\011-ts-master\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\012-react-forger\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\013-vue-sage\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\014-angular-weaver\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\015-node-crafter\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\016-flask-artist\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\017-django-master\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\018-fastapi-ace\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\019-sql-wizard\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\020-nosql-expert\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\021-git-guru\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\022-docker-maestro\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\023-kubernetes-captain\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\024-ci-cd-engineer\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\025-test-architect\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\026-debug-detectiv\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\027-perf-tuner\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\028-security-sentinel\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\029-auth-guardian\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\030-ml-practitioner\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\031-ai-architect\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\032-algorithm-master\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\033-data-struct-wiz\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\034-regex-ranger\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\035-cli-commander\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\036-graphql-ninja\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\037-rest-api-pro\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\038-websocket-mage\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\039-grpc-builder\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\040-microservice-arch\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\041-queue-master\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\042-cache-wizard\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\043-search-engineer\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\044-log-analyst\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\045-deploy-captain\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\046-cloud-architect\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\047-aws-specialist\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\048-azure-pro\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\049-gcp-expert\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\050-terraform-builder\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\051-ansible-crafter\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\052-vim-master\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\053-emacs-sage\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\054-shell-weaver\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\055-powershell-pro\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\056-network-engineer\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\057-encoding-expert\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\058-compression-wiz\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\059-image-processor\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\060-animation-crafter\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\061-game-dev-builder\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\062-mobile-dev-artist\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\063-responsive-master\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\064-a11y-advocate\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\065-seo-specialist\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\066-analytics-guru\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\067-i18n-master\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\068-l10n-expert\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\069-component-designer\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\070-design-system-arch\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\071-color-theorist\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\072-typography-master\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\073-layout-artist\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\074-svg-artist\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\075-canvas-wizard\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\076-webgl-builder\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\077-wasm-specialist\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\078-pwa-architect\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\079-meta-tag-master\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\080-html-craftsman\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\081-http-protocol-pro\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\082-json-validator\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\083-yaml-tamer\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\084-markdown-scribe\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\085-openapi-designer\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\086-proto-compiler\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\087-code-formatter\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\088-static-site-gen\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\089-jamstack-dev\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\090-cdn-specialist\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\091-webhook-builder\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\092-sse-crafter\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\093-oauth-guardian\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\094-jwt-master\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\095-rate-limiter\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\096-proxy-engineer\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\097-load-balancer\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\098-db-migrator\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\099-seed-data-pro\server.py" > NUL 2>&1
start /B python "G:\zed\mcp_servers\100-fullstack-dev\server.py" > NUL 2>&1
echo All 100 servers started.
